# File YAML untuk konfigurasi workflow CI/CD aplikasi Karsajobs frontend pada CircleCI
# untuk assignment Dicoding 2 - Membangun Arsitektur Microservices dengan Kubernetes
# Nama siswa: Lonard Steven - Jakarta

version: 2.1              # Menetapkan versi YML dari file konfigurasi YML

jobs:                                                                       # Definisi job yang akan dilakukan pada CircleCI
  lint-dockerfile:                                                          # Job 1 - lint-dockerfile: Menginstal Hadolint dan menggunakannya pada Dockerfile frontend
    docker:
      - image: cimg/base:2023.11
    steps: 
      - checkout                                                            # Lakukan checkout step
      - setup_remote_docker:                                                # Atur entity Docker yang dijalankan secara remote (dengan layer caching diaktifkan)
          docker_layer_caching: true
      - run: docker run --rm -i hadolint/hadolint < Dockerfile              # Pakai Hadolint untuk Dockerfile di repositori terkait                                           # Pakai Hadolint untuk Dockerfile di repositori terkait
  build-app-karsajobs-ui:                                                   # Job 2 - build-app-karsajobs-ui: Menjalankan file script untuk build dan push image
    docker:
      - image: cimg/base:2023.11                                            # Menggunakan image cimg base versi 2023.11
    steps:
      - checkout                                                            # Lakukan checkout step
      - setup_remote_docker:                                                # Atur kembali entity Docker yang dijalankan secara remote (dengan layer caching diaktifkan)
          docker_layer_caching: true
      - run: sh build_push_image_karsajobs_ui.sh                            # Jalankan shell file untuk build & push image karsajobs frontend

workflows:                                                                  # Alur kerja/workflow dari proses CI/CD yang dilakukan CircleCI, yakni:
  karsajobs-ui-cicd:
    jobs:
      - lint-dockerfile                                                     # Melakukan job 1 (lint-dockerfile) pertama-tama, dan
      - build-app-karsajobs-ui:                                             # Melakukan job 2 (build-app-karsajobs-ui) setelah job lint-dockerfile selesai dilakukan (dan berhasil)
          requires:
            - lint-dockerfile