# File YAML untuk konfigurasi workflow CI/CD aplikasi Karsajobs frontend pada CircleCI
# untuk assignment Dicoding 2 - Membangun Arsitektur Microservices dengan Kubernetes
# Nama siswa: Lonard Steven - Jakarta

version: 2.1              # Menetapkan versi YML dari file konfigurasi YML

jobs:                                                                       # Definisi job yang akan dilakukan pada CircleCI
  lint-dockerfile:                                                          # Job 1 - lint-dockerfile: Menginstal Hadolint dan menggunakannya pada Dockerfile frontend
    name: Install Hadolint and use it against the frontend Dockerfile
    command: 
    - image: hadolint/hadolint
    - run: hadolint Dockerfile
  build-app-karsajobs-ui:                                                   # Job 2 - build-app-karsajobs: Menjalankan file script untuk build dan push image
    name: Build and push the frontend app to the GitHub Package Registry!
    command:
    - run: sh build_push_image_karsajobs_ui.sh

  workflows:
    karsajobs-ui-cicd:
      jobs:
        - lint-dockerfile
        - build-app-karsajobs-ui:
            requires:
              - lint-dockerfile